---
- debug:
    msg: Installation de GCC par packages.

- name: Test de l'opération à effectuer.
  stat:
    path: /etc/ansible/facts.d/gcc.fact
  register: operation

- name: Ajout de nouveau dépots.
  yum:
    name: "{{ liste_depots }}"
    state: latest
    update_cache: yes

- name: Mise à jour du système.
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Installation de GCC en version packagé.
  yum:
    name: "{{ liste_packages }}"
    state: latest

- name: Création du script de configuration des symlinks.
  template:
    src: templates/alternat_package.j2
    dest: /root/alternat_package.sh
    backup: no
    owner: root
    group: root
    mode: 0700

- name: Exécution du script de configuration.
  shell: /root/alternat_package.sh
  args:
    executable: /bin/bash

- name: Suppression du script de configuration des symlinks.
  file:
    path: /root/alternat_package.sh
    state: absent

- name: Gestion d'erreur de copie de template.
  block:
    - name: Création du fichier facts (playbook).
      template:
        src: ../ficscommun/templates/fact.j2
        dest: /etc/ansible/facts.d/gcc.fact
        owner: root
        group: root
        backup: no
        mode: 0644
  rescue:
    - name: Création du fichier facts (site).
      template:
        src: ficscommun/templates/fact.j2
        dest: /etc/ansible/facts.d/gcc.fact
        owner: root
        group: root
        backup: no
        mode: 0644
  when: not operation.stat.exists

- name: Ecriture des fact.
  ini_file:
    path: /etc/ansible/facts.d/gcc.fact
    section: install
    option: "{{ item.option }}"
    value: "{{ item.valeur }}"
    mode: 0644
    backup: no
  with_items:
    - {option: 'playbook_version', valeur: "{{ version_playbook }}" }
    - {option: 'role_version', valeur: "{{ version_role }}" }
    - {option: 'gcc_version', valeur: "devtoolset" }
    - {option: 'jour_installation', valeur: "{{ ansible_date_time.weekday }}" }
    - {option: 'date_installation', valeur: "{{ ansible_date_time.day }}/{{ ansible_date_time.month }}/{{ ansible_date_time.year }}" }
    - {option: 'heure_installation', valeur: "{{ ansible_date_time.time }}" }

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    reboot_timeout: 300
