---
- name: Installation / mise à jour du tronc commun en cours.
  hosts: "{{ cible }}"
  remote_user: root
  gather_facts: yes
  roles:
    - troncommun

- name: Installation / mise à jour du compilateur GCC en cours.
  hosts: "{{ cible }}"
  remote_user: root
  gather_facts: yes
  roles:
    - gcc
